version: '3'
services:
    metabase:
        image: metabase_img
        volumes: 
            - ./volumes/metabase:/metabase-data 
        ports:
            - 3000:3000
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=postgres_metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=sys-sigti@weg.net
            - MB_DB_PASS=@TiWegKPI2021
            - MB_DB_HOST=postgres
            - MB_DB_FILE=/metabase-data/metabase.db
        depends_on:
            - postgres
        networks:
            - metabase         

    postgres:            
        image: postgres:9.6.22
        ports:
            - 5432:5432        
        environment:
            - POSTGRES_USER=sys-sigti@weg.net
            - POSTGRES_PASSWORD=@TiWegKPI2021
            - POSTGRES_DB=postgres_metabase
        networks:
            - metabase 

    pgadmin:
        image: dpage/pgadmin4:5.4
        restart: always
        ports:
            - 8080:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=sys-sigti@weg.net
            - PGADMIN_DEFAULT_PASSWORD=@TiWegKPI2021
        depends_on:
            - postgres
        networks:
            - metabase             

networks:
    metabase: