version: '3'
services:
    metabase:
        image: metabase_img
        restart: always
        volumes: 
            - ./volumes/metabase:/metabase-data 
        ports:
            - 3000:3000
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=sys-sigti@weg.net
            - MB_DB_PASS=@TiWegKPI2021
            - MB_DB_HOST=postgres
        command: 
            - createdb --encoding=UTF8 -e metabase
        depends_on:
            - postgres     

    postgres:            
        image: postgres:9.6.22
        restart: always
        volumes: 
            - ./volumes/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432        
        environment:
            - POSTGRES_USER=adminp
            - POSTGRES_PASSWORD=adminp
            - POSTGRES_DB=postgres_metabase


    pgadmin:
        image: dpage/pgadmin4:5.4
        restart: always
        ports:
            - 8080:8080
        environment:
            - PGADMIN_DEFAULT_EMAIL=sys-sigti@weg.net
            - PGADMIN_DEFAULT_PASSWORD=@TiWegKPI2021
        depends_on:
            - postgres
